{% set name = "napatrackmater" %}
{% set version = "3.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napatrackmater-{{ version }}.tar.gz
  sha256: d29ef787f24b9ba993f01c4f04f34418ffc432700dfd84308061f23153d1804c

build:
  entry_points:
    - track = napatrackmater.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dask-core
    - ffmpeg-python
    - imageio-ffmpeg
    - lmfit
    - matplotlib-base
    - napari
    - natsort
    - numpy
    - pandas
    - perfmetrics
    - python >=3.7
    - qtpy
    - scikit-image
    - scipy
    - seaborn
    - tifffile

test:
  imports:
    - napatrackmater
  commands:
    - pip list
    - pip check
    - track --help
  requires:
    - pip

about:
  home: https://github.com/kapoorlab/NapaTrackMater/
  summary: Import Trackmate XML files for Track Visualization and analysis in Napari.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
