{% set name = "napatrackmater" %}
{% set version = "5.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napatrackmater-{{ version }}.tar.gz
  sha256: 8b6b980ec4017e7d8fbbde89334e8ae6ad2c6b72420443d1797ce57e8d3eed4e

build:
  entry_points:
    - track = napatrackmater.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dask-core
    - ffmpeg-python
    - imageio-ffmpeg
    - lmfit
    - matplotlib-base
    - napari
    - natsort
    - numpy
    - pandas
    - perfmetrics
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - scipy
    - seaborn
    - tifffile

test:
  imports:
    - napatrackmater
  commands:
    - pip list
    - pip check
    - track --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kapoorlab/NapaTrackMater/
  summary: Import Trackmate XML files for Track Visualization and analysis in Napari.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
